### ISSUE TITLE
YTS RSS Feed

### ISSUE THREAD

**Issue by Minoritasia** [hyPnOtICDo0g/rss-chan#8]
Hi,

Since the YTS RSS feed always leads to main URL instead of direct torrent URL and breaks the auto mirroring, which codes should I edit to replace;

From this:
**Influence (2020) [WEBRip] [720p] [YTS.MX]**
https://yts.mx/movies/influence-2020

To this:
**Influence (2020) [WEBRip] [720p] [YTS.MX]**
https://yts.mx/torrent/download/E605F583298C3DAAC17B1B79E30DB3C4A8E99B8A

To test it out I'm thinking to change to this line to find out the output:
https://github.com/hyPnOtICDo0g/rss-chan/blob/c8ec3ddc05dd1e56991f1208197345757c529046/bot/modules/rsshandler.py#L50

And for final part to this line:
https://github.com/hyPnOtICDo0g/rss-chan/blob/c8ec3ddc05dd1e56991f1208197345757c529046/bot/modules/rsshandler.py#L120

I found a workaround to this issue in another [RSS Repo](https://github.com/viperadnan-git/rss-feed-telegram-bot) but not on yours.

Any feedback and help would be appreciated. Thank you!

**Comment by hyPnOtICDo0g** [comment]
@Minoritasia 
Editing either of those two lines will break the program if you use it for **any other feeds** apart from the one you listed right now. When you subscribe to a feed, the latest feed item will be written to the database. 
 
>To this:
Influence (2020) [WEBRip] [720p] [YTS.MX]
https://yts.mx/torrent/download/E605F583298C3DAAC17B1B79E30DB3C4A8E99B8A

The URL you listed above is present in the `<enclosures>` tag. If you're using the bot **exclusively** for this purpose, you'll have to make changes at a few places to prevent it from breaking. You can look into LN 50, 67, 68 and 117 & edit as you see it. 

This will work as you're updating the database with the latest item in the `<link>` tag & sending the item in the `<enclosures>` tag to your telegram chat. Since your feed contains both, it won't break.

But I suggest until you wait until #2 is implemented. Have a great day!
